
name: Kartik Offshore Job Monitor

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 7:30 AM India time

jobs:
  find-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run offshore job script
        run:  python job_bot.py

      - name: Upload results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: offshore-jobs-result
          path: offshore_jobs.txt
